version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:27"
      timezone: Etc/UTC
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: chore
