use super::{Field, Mode, Table};

pub const TABLES: &[Table] = &[
    Table {
        key: "gloAux",
        count_at: 0,
        src_base: 1,
        src_stride: 3,
        dst_base: 29,
        dst_stride: 4,
        capacity: 64,
        count_slot: 28,
        count_width: 1,
        fields: &[
            Field(0, 1, Mode::Raw, 0, 1),
            Field(1, 1, Mode::Raw, 2, 1),
            Field(2, 1, Mode::Constant, 1, 0),
            Field(3, 1, Mode::Raw, 1, 1),
        ],
    },
    Table {
        key: "gpsRti",
        count_at: 10,
        src_base: 11,
        src_stride: 7,
        dst_base: 306,
        dst_stride: 8,
        capacity: 32,
        count_slot: 304,
        count_width: 2,
        fields: &[
            Field(0, 1, Mode::Raw, 0, 1),
            Field(1, 1, Mode::Raw, 1, 1),
            Field(2, 2, Mode::BigEndian, 2, 2),
            Field(4, 2, Mode::BigEndian, 4, 2),
            Field(6, 2, Mode::BigEndian, 6, 1),
        ],
    },
    Table {
        key: "gloRti",
        count_at: 0,
        src_base: 1,
        src_stride: 3,
        dst_base: 574,
        dst_stride: 4,
        capacity: 64,
        count_slot: 572,
        count_width: 2,
        fields: &[
            Field(0, 2, Mode::BigEndian, 0, 1),
            Field(2, 2, Mode::BigEndian, 1, 2),
        ],
    },
    Table {
        key: "galRti",
        count_at: 0,
        src_base: 1,
        src_stride: 3,
        dst_base: 838,
        dst_stride: 4,
        capacity: 64,
        count_slot: 836,
        count_width: 2,
        fields: &[
            Field(0, 2, Mode::BigEndian, 0, 1),
            Field(2, 2, Mode::BigEndian, 1, 2),
        ],
    },
    Table {
        key: "bdsRti",
        count_at: 0,
        src_base: 1,
        src_stride: 3,
        dst_base: 1102,
        dst_stride: 4,
        capacity: 64,
        count_slot: 1100,
        count_width: 2,
        fields: &[
            Field(0, 2, Mode::BigEndian, 0, 1),
            Field(2, 2, Mode::BigEndian, 1, 2),
        ],
    },
    Table {
        key: "gpsAlm",
        count_at: 2,
        src_base: 3,
        src_stride: 31,
        dst_base: 1364,
        dst_stride: 32,
        capacity: 32,
        count_slot: 1361,
        count_width: 1,
        fields: &[
            Field(0, 2, Mode::BigEndian, 0, 1),
            Field(2, 2, Mode::BigEndian, 1, 2),
            Field(4, 2, Mode::LowByte, 3, 2),
            Field(6, 2, Mode::BigEndian, 5, 2),
            Field(8, 2, Mode::BigEndian, 7, 2),
            Field(10, 2, Mode::LowByte, 9, 2),
            Field(12, 4, Mode::BigEndian, 11, 4),
            Field(16, 4, Mode::BigEndian, 15, 4),
            Field(20, 4, Mode::BigEndian, 19, 4),
            Field(24, 4, Mode::BigEndian, 23, 4),
            Field(28, 2, Mode::BigEndian, 27, 2),
            Field(30, 2, Mode::BigEndian, 29, 2),
        ],
    },
    Table {
        key: "gloAlm",
        count_at: 0,
        src_base: 4,
        src_stride: 29,
        dst_base: 2392,
        dst_stride: 32,
        capacity: 24,
        count_slot: 2388,
        count_width: 1,
        fields: &[
            Field(0, 2, Mode::BigEndian, 0, 2),
            Field(2, 1, Mode::Raw, 2, 1),
            Field(3, 1, Mode::Raw, 3, 1),
            Field(4, 4, Mode::BigEndian, 4, 4),
            Field(8, 4, Mode::BigEndian, 8, 4),
            Field(12, 4, Mode::BigEndian, 12, 4),
            Field(16, 4, Mode::BigEndian, 16, 4),
            Field(20, 2, Mode::BigEndian, 20, 1),
            Field(22, 2, Mode::BigEndian, 21, 2),
            Field(26, 2, Mode::BigEndian, 25, 2),
            Field(28, 1, Mode::Raw, 27, 1),
            Field(29, 1, Mode::Raw, 28, 1),
        ],
    },
    Table {
        key: "galAlm",
        count_at: 0,
        src_base: 6,
        src_stride: 21,
        dst_base: 3168,
        dst_stride: 22,
        capacity: 36,
        count_slot: 3160,
        count_width: 1,
        fields: &[
            Field(0, 2, Mode::BigEndian, 0, 1),
            Field(2, 2, Mode::BigEndian, 1, 2),
            Field(4, 2, Mode::BigEndian, 3, 2),
            Field(6, 2, Mode::BigEndian, 5, 2),
            Field(8, 1, Mode::Raw, 7, 1),
            Field(9, 1, Mode::Raw, 8, 1),
            Field(10, 2, Mode::BigEndian, 9, 2),
            Field(12, 2, Mode::BigEndian, 11, 2),
            Field(14, 2, Mode::BigEndian, 13, 2),
            Field(16, 2, Mode::BigEndian, 15, 2),
            Field(18, 2, Mode::BigEndian, 17, 2),
            Field(20, 2, Mode::BigEndian, 19, 2),
        ],
    },
    Table {
        key: "bdsAlm",
        count_at: 0,
        src_base: 4,
        src_stride: 34,
        dst_base: 3964,
        dst_stride: 36,
        capacity: 63,
        count_slot: 3960,
        count_width: 1,
        fields: &[
            Field(0, 1, Mode::Raw, 0, 1),
            Field(1, 1, Mode::Raw, 1, 1),
            Field(4, 4, Mode::BigEndian, 2, 4),
            Field(8, 4, Mode::BigEndian, 6, 4),
            Field(12, 4, Mode::BigEndian, 10, 4),
            Field(16, 4, Mode::BigEndian, 14, 4),
            Field(20, 4, Mode::BigEndian, 18, 4),
            Field(24, 4, Mode::BigEndian, 22, 4),
            Field(28, 2, Mode::BigEndian, 26, 2),
            Field(30, 2, Mode::BigEndian, 28, 2),
            Field(32, 2, Mode::BigEndian, 30, 2),
            Field(34, 2, Mode::BigEndian, 32, 2),
        ],
    },
];
