use super::Field;
use crate::policy::System;

pub fn fields(system: System) -> &'static [Field] {
    match system {
        System::Gps => &[
            Field {
                name: "sv",
                offset: 0,
                bytes: 2,
                signed: false,
                scale: 1.0,
            },
            Field {
                name: "week",
                offset: 2,
                bytes: 2,
                signed: false,
                scale: 1.0,
            },
            Field {
                name: "m0",
                offset: 8,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "delta_n",
                offset: 12,
                bytes: 2,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "ecc",
                offset: 16,
                bytes: 4,
                signed: false,
                scale: 1.1641532182693481e-10,
            },
            Field {
                name: "sqrt_a",
                offset: 20,
                bytes: 4,
                signed: false,
                scale: 1.9073486328125e-06,
            },
            Field {
                name: "omega0",
                offset: 24,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "i0",
                offset: 28,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "omega",
                offset: 32,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "omegadot",
                offset: 36,
                bytes: 4,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "idot",
                offset: 40,
                bytes: 2,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "cuc",
                offset: 42,
                bytes: 2,
                signed: true,
                scale: 1.862645149230957e-09,
            },
            Field {
                name: "cus",
                offset: 44,
                bytes: 2,
                signed: true,
                scale: 1.862645149230957e-09,
            },
            Field {
                name: "crc",
                offset: 46,
                bytes: 2,
                signed: true,
                scale: 0.03125,
            },
            Field {
                name: "crs",
                offset: 48,
                bytes: 2,
                signed: true,
                scale: 0.03125,
            },
            Field {
                name: "cic",
                offset: 50,
                bytes: 2,
                signed: true,
                scale: 1.862645149230957e-09,
            },
            Field {
                name: "cis",
                offset: 52,
                bytes: 2,
                signed: true,
                scale: 1.862645149230957e-09,
            },
            Field {
                name: "tgd",
                offset: 54,
                bytes: 1,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "af0",
                offset: 56,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "af1",
                offset: 60,
                bytes: 4,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "toc",
                offset: 72,
                bytes: 2,
                signed: false,
                scale: 16.0,
            },
            Field {
                name: "toe",
                offset: 74,
                bytes: 2,
                signed: false,
                scale: 16.0,
            },
            Field {
                name: "unk4c",
                offset: 76,
                bytes: 4,
                signed: false,
                scale: 1.0,
            },
        ],
        System::Galileo => &[
            Field {
                name: "sv",
                offset: 0,
                bytes: 2,
                signed: false,
                scale: 1.0,
            },
            Field {
                name: "toc",
                offset: 4,
                bytes: 4,
                signed: false,
                scale: 60.0,
            },
            Field {
                name: "af1",
                offset: 12,
                bytes: 4,
                signed: true,
                scale: 1.4210854715202004e-14,
            },
            Field {
                name: "af0",
                offset: 16,
                bytes: 4,
                signed: true,
                scale: 5.820766091346741e-11,
            },
            Field {
                name: "tgd",
                offset: 20,
                bytes: 2,
                signed: true,
                scale: 2.3283064365386963e-10,
            },
            Field {
                name: "toe",
                offset: 24,
                bytes: 4,
                signed: false,
                scale: 60.0,
            },
            Field {
                name: "omega",
                offset: 28,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "delta_n",
                offset: 32,
                bytes: 2,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "m0",
                offset: 36,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "omegadot",
                offset: 40,
                bytes: 4,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "ecc",
                offset: 44,
                bytes: 4,
                signed: false,
                scale: 1.1641532182693481e-10,
            },
            Field {
                name: "idot",
                offset: 48,
                bytes: 2,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "sqrt_a",
                offset: 52,
                bytes: 4,
                signed: false,
                scale: 1.9073486328125e-06,
            },
            Field {
                name: "i0",
                offset: 56,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "omega0",
                offset: 60,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "crs",
                offset: 64,
                bytes: 2,
                signed: true,
                scale: 0.03125,
            },
            Field {
                name: "cis",
                offset: 66,
                bytes: 2,
                signed: true,
                scale: 1.862645149230957e-09,
            },
            Field {
                name: "cus",
                offset: 68,
                bytes: 2,
                signed: true,
                scale: 1.862645149230957e-09,
            },
            Field {
                name: "crc",
                offset: 70,
                bytes: 2,
                signed: true,
                scale: 0.03125,
            },
            Field {
                name: "cic",
                offset: 72,
                bytes: 2,
                signed: true,
                scale: 1.862645149230957e-09,
            },
            Field {
                name: "cuc",
                offset: 74,
                bytes: 2,
                signed: true,
                scale: 1.862645149230957e-09,
            },
        ],
        System::Bds => &[
            Field {
                name: "sv",
                offset: 0,
                bytes: 2,
                signed: false,
                scale: 1.0,
            },
            Field {
                name: "toe_tag",
                offset: 2,
                bytes: 2,
                signed: false,
                scale: 1.0,
            },
            Field {
                name: "toe",
                offset: 8,
                bytes: 4,
                signed: false,
                scale: 8.0,
            },
            Field {
                name: "af0",
                offset: 12,
                bytes: 4,
                signed: true,
                scale: 1.1641532182693481e-10,
            },
            Field {
                name: "af1",
                offset: 16,
                bytes: 4,
                signed: true,
                scale: 8.881784197001252e-16,
            },
            Field {
                name: "af2",
                offset: 20,
                bytes: 2,
                signed: true,
                scale: 1.3552527156068805e-20,
            },
            Field {
                name: "tgd1",
                offset: 22,
                bytes: 2,
                signed: true,
                scale: 1e-10,
            },
            Field {
                name: "tgd2",
                offset: 24,
                bytes: 2,
                signed: true,
                scale: 1e-10,
            },
            Field {
                name: "toc",
                offset: 28,
                bytes: 4,
                signed: false,
                scale: 8.0,
            },
            Field {
                name: "sqrt_a",
                offset: 32,
                bytes: 4,
                signed: false,
                scale: 1.9073486328125e-06,
            },
            Field {
                name: "ecc",
                offset: 36,
                bytes: 4,
                signed: false,
                scale: 1.1641532182693481e-10,
            },
            Field {
                name: "omega",
                offset: 40,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "delta_n",
                offset: 44,
                bytes: 2,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "m0",
                offset: 48,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "omega0",
                offset: 52,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "omegadot",
                offset: 56,
                bytes: 4,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "i0",
                offset: 60,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "idot",
                offset: 64,
                bytes: 2,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "cuc",
                offset: 68,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "cus",
                offset: 72,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "crc",
                offset: 76,
                bytes: 4,
                signed: true,
                scale: 0.015625,
            },
            Field {
                name: "crs",
                offset: 80,
                bytes: 4,
                signed: true,
                scale: 0.015625,
            },
            Field {
                name: "cic",
                offset: 84,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "cis",
                offset: 88,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
        ],
        System::Qzs => &[
            Field {
                name: "sv",
                offset: 0,
                bytes: 2,
                signed: false,
                scale: 1.0,
            },
            Field {
                name: "toc",
                offset: 4,
                bytes: 4,
                signed: false,
                scale: 16.0,
            },
            Field {
                name: "af1",
                offset: 12,
                bytes: 4,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "af0",
                offset: 16,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "tgd",
                offset: 20,
                bytes: 1,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "toe",
                offset: 24,
                bytes: 4,
                signed: false,
                scale: 16.0,
            },
            Field {
                name: "omega",
                offset: 28,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "delta_n",
                offset: 32,
                bytes: 2,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "m0",
                offset: 36,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "omegadot",
                offset: 40,
                bytes: 4,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "ecc",
                offset: 44,
                bytes: 4,
                signed: false,
                scale: 1.1641532182693481e-10,
            },
            Field {
                name: "idot",
                offset: 48,
                bytes: 2,
                signed: true,
                scale: 1.1368683772161603e-13,
            },
            Field {
                name: "sqrt_a",
                offset: 52,
                bytes: 4,
                signed: false,
                scale: 1.9073486328125e-06,
            },
            Field {
                name: "i0",
                offset: 56,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "omega0",
                offset: 60,
                bytes: 4,
                signed: true,
                scale: 4.656612873077393e-10,
            },
            Field {
                name: "crs",
                offset: 64,
                bytes: 2,
                signed: true,
                scale: 0.03125,
            },
            Field {
                name: "cis",
                offset: 66,
                bytes: 2,
                signed: true,
                scale: 1.862645149230957e-09,
            },
            Field {
                name: "cus",
                offset: 68,
                bytes: 2,
                signed: true,
                scale: 1.862645149230957e-09,
            },
            Field {
                name: "crc",
                offset: 70,
                bytes: 2,
                signed: true,
                scale: 0.03125,
            },
            Field {
                name: "cic",
                offset: 72,
                bytes: 2,
                signed: true,
                scale: 1.862645149230957e-09,
            },
            Field {
                name: "cuc",
                offset: 74,
                bytes: 2,
                signed: true,
                scale: 1.862645149230957e-09,
            },
        ],
        System::Glonass => &[
            Field {
                name: "slot",
                offset: 0,
                bytes: 2,
                signed: false,
                scale: 1.0,
            },
            Field {
                name: "t_b",
                offset: 2,
                bytes: 2,
                signed: false,
                scale: 900.0,
            },
            Field {
                name: "tau_n",
                offset: 4,
                bytes: 4,
                signed: true,
                scale: 9.313225746154785e-10,
            },
            Field {
                name: "gamma_n",
                offset: 8,
                bytes: 4,
                signed: true,
                scale: 9.094947017729282e-13,
            },
            Field {
                name: "flag",
                offset: 12,
                bytes: 4,
                signed: true,
                scale: 1.0,
            },
            Field {
                name: "x",
                offset: 16,
                bytes: 4,
                signed: true,
                scale: 0.00048828125,
            },
            Field {
                name: "vx",
                offset: 20,
                bytes: 4,
                signed: true,
                scale: 9.5367431640625e-07,
            },
            Field {
                name: "ax",
                offset: 24,
                bytes: 1,
                signed: true,
                scale: 9.313225746154785e-10,
            },
            Field {
                name: "y",
                offset: 28,
                bytes: 4,
                signed: true,
                scale: 0.00048828125,
            },
            Field {
                name: "vy",
                offset: 32,
                bytes: 4,
                signed: true,
                scale: 9.5367431640625e-07,
            },
            Field {
                name: "ay",
                offset: 36,
                bytes: 1,
                signed: true,
                scale: 9.313225746154785e-10,
            },
            Field {
                name: "z",
                offset: 40,
                bytes: 4,
                signed: true,
                scale: 0.00048828125,
            },
            Field {
                name: "vz",
                offset: 44,
                bytes: 4,
                signed: true,
                scale: 9.5367431640625e-07,
            },
            Field {
                name: "az",
                offset: 48,
                bytes: 1,
                signed: true,
                scale: 9.313225746154785e-10,
            },
        ],
    }
}
