use super::{Field, Kind};

pub fn fields(message: u16) -> Option<&'static [Field]> {
    match message {
        1019 => Some(&[
            Field {
                name: "prn",
                width: 6,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "week",
                width: 10,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "ura",
                width: 4,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "code_l2",
                width: 2,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "idot",
                width: 14,
                kind: Kind::Signed,
                scale: 1.1368683772161603e-13,
                bias: 0.0,
            },
            Field {
                name: "iode",
                width: 8,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "toc",
                width: 16,
                kind: Kind::Unsigned,
                scale: 16.0,
                bias: 0.0,
            },
            Field {
                name: "af2",
                width: 8,
                kind: Kind::Signed,
                scale: 2.7755575615628914e-17,
                bias: 0.0,
            },
            Field {
                name: "af1",
                width: 16,
                kind: Kind::Signed,
                scale: 1.1368683772161603e-13,
                bias: 0.0,
            },
            Field {
                name: "af0",
                width: 22,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "iodc",
                width: 10,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "crs",
                width: 16,
                kind: Kind::Signed,
                scale: 0.03125,
                bias: 0.0,
            },
            Field {
                name: "delta_n",
                width: 16,
                kind: Kind::Signed,
                scale: 1.1368683772161603e-13,
                bias: 0.0,
            },
            Field {
                name: "m0",
                width: 32,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "cuc",
                width: 16,
                kind: Kind::Signed,
                scale: 1.862645149230957e-09,
                bias: 0.0,
            },
            Field {
                name: "ecc",
                width: 32,
                kind: Kind::Unsigned,
                scale: 1.1641532182693481e-10,
                bias: 0.0,
            },
            Field {
                name: "cus",
                width: 16,
                kind: Kind::Signed,
                scale: 1.862645149230957e-09,
                bias: 0.0,
            },
            Field {
                name: "sqrt_a",
                width: 32,
                kind: Kind::Unsigned,
                scale: 1.9073486328125e-06,
                bias: 0.0,
            },
            Field {
                name: "toe",
                width: 16,
                kind: Kind::Unsigned,
                scale: 16.0,
                bias: 0.0,
            },
            Field {
                name: "cic",
                width: 16,
                kind: Kind::Signed,
                scale: 1.862645149230957e-09,
                bias: 0.0,
            },
            Field {
                name: "omega0",
                width: 32,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "cis",
                width: 16,
                kind: Kind::Signed,
                scale: 1.862645149230957e-09,
                bias: 0.0,
            },
            Field {
                name: "i0",
                width: 32,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "crc",
                width: 16,
                kind: Kind::Signed,
                scale: 0.03125,
                bias: 0.0,
            },
            Field {
                name: "omega",
                width: 32,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "omegadot",
                width: 24,
                kind: Kind::Signed,
                scale: 1.1368683772161603e-13,
                bias: 0.0,
            },
            Field {
                name: "tgd",
                width: 8,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "health",
                width: 6,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "l2p",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "fit",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
        ]),
        1020 => Some(&[
            Field {
                name: "slot",
                width: 6,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "freq",
                width: 5,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 7.0,
            },
            Field {
                name: "alm_health",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "alm_health_avail",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "p1",
                width: 2,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "tk",
                width: 12,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "bn_msb",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "p2",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "tb",
                width: 7,
                kind: Kind::Unsigned,
                scale: 900.0,
                bias: 0.0,
            },
            Field {
                name: "vx",
                width: 24,
                kind: Kind::SignMagnitude,
                scale: 9.5367431640625e-07,
                bias: 0.0,
            },
            Field {
                name: "x",
                width: 27,
                kind: Kind::SignMagnitude,
                scale: 0.00048828125,
                bias: 0.0,
            },
            Field {
                name: "ax",
                width: 5,
                kind: Kind::SignMagnitude,
                scale: 9.313225746154785e-10,
                bias: 0.0,
            },
            Field {
                name: "vy",
                width: 24,
                kind: Kind::SignMagnitude,
                scale: 9.5367431640625e-07,
                bias: 0.0,
            },
            Field {
                name: "y",
                width: 27,
                kind: Kind::SignMagnitude,
                scale: 0.00048828125,
                bias: 0.0,
            },
            Field {
                name: "ay",
                width: 5,
                kind: Kind::SignMagnitude,
                scale: 9.313225746154785e-10,
                bias: 0.0,
            },
            Field {
                name: "vz",
                width: 24,
                kind: Kind::SignMagnitude,
                scale: 9.5367431640625e-07,
                bias: 0.0,
            },
            Field {
                name: "z",
                width: 27,
                kind: Kind::SignMagnitude,
                scale: 0.00048828125,
                bias: 0.0,
            },
            Field {
                name: "az",
                width: 5,
                kind: Kind::SignMagnitude,
                scale: 9.313225746154785e-10,
                bias: 0.0,
            },
            Field {
                name: "p3",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "gamma_n",
                width: 11,
                kind: Kind::SignMagnitude,
                scale: 9.094947017729282e-13,
                bias: 0.0,
            },
            Field {
                name: "p",
                width: 2,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "ln3",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "tau_n",
                width: 22,
                kind: Kind::SignMagnitude,
                scale: 9.313225746154785e-10,
                bias: 0.0,
            },
            Field {
                name: "dtau_n",
                width: 5,
                kind: Kind::SignMagnitude,
                scale: 9.313225746154785e-10,
                bias: 0.0,
            },
            Field {
                name: "en",
                width: 5,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "p4",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "ft",
                width: 4,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "nt",
                width: 11,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "m",
                width: 2,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "add_avail",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "na",
                width: 11,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "tau_c",
                width: 32,
                kind: Kind::SignMagnitude,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "n4",
                width: 5,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "tau_gps",
                width: 22,
                kind: Kind::SignMagnitude,
                scale: 9.313225746154785e-10,
                bias: 0.0,
            },
            Field {
                name: "ln5",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
        ]),
        1042 => Some(&[
            Field {
                name: "prn",
                width: 6,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "week",
                width: 13,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "urai",
                width: 4,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "idot",
                width: 14,
                kind: Kind::Signed,
                scale: 1.1368683772161603e-13,
                bias: 0.0,
            },
            Field {
                name: "aode",
                width: 5,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "toc",
                width: 17,
                kind: Kind::Unsigned,
                scale: 8.0,
                bias: 0.0,
            },
            Field {
                name: "af2",
                width: 11,
                kind: Kind::Signed,
                scale: 1.3552527156068805e-20,
                bias: 0.0,
            },
            Field {
                name: "af1",
                width: 22,
                kind: Kind::Signed,
                scale: 8.881784197001252e-16,
                bias: 0.0,
            },
            Field {
                name: "af0",
                width: 24,
                kind: Kind::Signed,
                scale: 1.1641532182693481e-10,
                bias: 0.0,
            },
            Field {
                name: "aodc",
                width: 5,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "crs",
                width: 18,
                kind: Kind::Signed,
                scale: 0.015625,
                bias: 0.0,
            },
            Field {
                name: "delta_n",
                width: 16,
                kind: Kind::Signed,
                scale: 1.1368683772161603e-13,
                bias: 0.0,
            },
            Field {
                name: "m0",
                width: 32,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "cuc",
                width: 18,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "ecc",
                width: 32,
                kind: Kind::Unsigned,
                scale: 1.1641532182693481e-10,
                bias: 0.0,
            },
            Field {
                name: "cus",
                width: 18,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "sqrt_a",
                width: 32,
                kind: Kind::Unsigned,
                scale: 1.9073486328125e-06,
                bias: 0.0,
            },
            Field {
                name: "toe",
                width: 17,
                kind: Kind::Unsigned,
                scale: 8.0,
                bias: 0.0,
            },
            Field {
                name: "cic",
                width: 18,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "omega0",
                width: 32,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "cis",
                width: 18,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "i0",
                width: 32,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "crc",
                width: 18,
                kind: Kind::Signed,
                scale: 0.015625,
                bias: 0.0,
            },
            Field {
                name: "omega",
                width: 32,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "omegadot",
                width: 24,
                kind: Kind::Signed,
                scale: 1.1368683772161603e-13,
                bias: 0.0,
            },
            Field {
                name: "tgd1",
                width: 10,
                kind: Kind::Signed,
                scale: 1e-10,
                bias: 0.0,
            },
            Field {
                name: "tgd2",
                width: 10,
                kind: Kind::Signed,
                scale: 1e-10,
                bias: 0.0,
            },
            Field {
                name: "health",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
        ]),
        1046 => Some(&[
            Field {
                name: "prn",
                width: 6,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "week",
                width: 12,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "iodnav",
                width: 10,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "sisa",
                width: 8,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "idot",
                width: 14,
                kind: Kind::Signed,
                scale: 1.1368683772161603e-13,
                bias: 0.0,
            },
            Field {
                name: "toc",
                width: 14,
                kind: Kind::Unsigned,
                scale: 60.0,
                bias: 0.0,
            },
            Field {
                name: "af2",
                width: 6,
                kind: Kind::Signed,
                scale: 1.734723475976807e-18,
                bias: 0.0,
            },
            Field {
                name: "af1",
                width: 21,
                kind: Kind::Signed,
                scale: 1.4210854715202004e-14,
                bias: 0.0,
            },
            Field {
                name: "af0",
                width: 31,
                kind: Kind::Signed,
                scale: 5.820766091346741e-11,
                bias: 0.0,
            },
            Field {
                name: "crs",
                width: 16,
                kind: Kind::Signed,
                scale: 0.03125,
                bias: 0.0,
            },
            Field {
                name: "delta_n",
                width: 16,
                kind: Kind::Signed,
                scale: 1.1368683772161603e-13,
                bias: 0.0,
            },
            Field {
                name: "m0",
                width: 32,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "cuc",
                width: 16,
                kind: Kind::Signed,
                scale: 1.862645149230957e-09,
                bias: 0.0,
            },
            Field {
                name: "ecc",
                width: 32,
                kind: Kind::Unsigned,
                scale: 1.1641532182693481e-10,
                bias: 0.0,
            },
            Field {
                name: "cus",
                width: 16,
                kind: Kind::Signed,
                scale: 1.862645149230957e-09,
                bias: 0.0,
            },
            Field {
                name: "sqrt_a",
                width: 32,
                kind: Kind::Unsigned,
                scale: 1.9073486328125e-06,
                bias: 0.0,
            },
            Field {
                name: "toe",
                width: 14,
                kind: Kind::Unsigned,
                scale: 60.0,
                bias: 0.0,
            },
            Field {
                name: "cic",
                width: 16,
                kind: Kind::Signed,
                scale: 1.862645149230957e-09,
                bias: 0.0,
            },
            Field {
                name: "omega0",
                width: 32,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "cis",
                width: 16,
                kind: Kind::Signed,
                scale: 1.862645149230957e-09,
                bias: 0.0,
            },
            Field {
                name: "i0",
                width: 32,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "crc",
                width: 16,
                kind: Kind::Signed,
                scale: 0.03125,
                bias: 0.0,
            },
            Field {
                name: "omega",
                width: 32,
                kind: Kind::Signed,
                scale: 4.656612873077393e-10,
                bias: 0.0,
            },
            Field {
                name: "omegadot",
                width: 24,
                kind: Kind::Signed,
                scale: 1.1368683772161603e-13,
                bias: 0.0,
            },
            Field {
                name: "bgd_e5a",
                width: 10,
                kind: Kind::Signed,
                scale: 2.3283064365386963e-10,
                bias: 0.0,
            },
            Field {
                name: "bgd_e5b",
                width: 10,
                kind: Kind::Signed,
                scale: 2.3283064365386963e-10,
                bias: 0.0,
            },
            Field {
                name: "e5b_health",
                width: 2,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "e5b_valid",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "e1b_health",
                width: 2,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "e1b_valid",
                width: 1,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
        ]),
        4056 => Some(&[
            Field {
                name: "tag",
                width: 12,
                kind: Kind::Unsigned,
                scale: 1.0,
                bias: 0.0,
            },
            Field {
                name: "alpha0",
                width: 8,
                kind: Kind::Signed,
                scale: 9.313225746154785e-10,
                bias: 0.0,
            },
            Field {
                name: "alpha1",
                width: 8,
                kind: Kind::Signed,
                scale: 7.450580596923828e-09,
                bias: 0.0,
            },
            Field {
                name: "alpha2",
                width: 8,
                kind: Kind::Signed,
                scale: 5.960464477539063e-08,
                bias: 0.0,
            },
            Field {
                name: "alpha3",
                width: 8,
                kind: Kind::Signed,
                scale: 5.960464477539063e-08,
                bias: 0.0,
            },
            Field {
                name: "beta0",
                width: 8,
                kind: Kind::Signed,
                scale: 2048.0,
                bias: 0.0,
            },
            Field {
                name: "beta1",
                width: 8,
                kind: Kind::Signed,
                scale: 16384.0,
                bias: 0.0,
            },
            Field {
                name: "beta2",
                width: 8,
                kind: Kind::Signed,
                scale: 65536.0,
                bias: 0.0,
            },
            Field {
                name: "beta3",
                width: 8,
                kind: Kind::Signed,
                scale: 65536.0,
                bias: 0.0,
            },
        ]),
        _ => None,
    }
}
